backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

identity:
  roles:
    - admin

collections:
  - name: "projects"
    label: "Projects"
    folder: "uploads/projects"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
